[project]
name = "ormit-art"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.36.0",
    "pymupdf>=1.26.4",
    "pypdf>=6.0.0",
    "pyqt6>=6.9.1",
    "python-docx>=1.2.0",
]
